plugins {
    id 'java'
    id 'eclipse'
    id 'org.cadixdev.licenser' version '0.6.1'
    id 'com.diffplug.spotless' version '6.13.0'
    id 'net.minecraftforge.gradle' version '6.+'
    // id 'net.galacticraft.changelog' version '1.0.4'
    // id 'net.galacticraft.internal.legacy' version '1.0.5'
    // id 'nexus-publishing' version '2.1'
}

group = "dev.galacticraft"
archivesBaseName = "Galacticraft"
version = "${mod_version}${version_suffix}"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

configurations {
    compileRequired
    implementation.extendsFrom compileRequired
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    
    runs {
        client {
            workingDirectory project.file('run/client')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            jvmArgs '-Xmx3G', '-Dfml.coreMods.load=micdoodle8.mods.miccore.MicdoodlePlugin'
        }
        server {
            workingDirectory project.file('run/server')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            jvmArgs '-Xmx3G', '-Dfml.coreMods.load=micdoodle8.mods.miccore.MicdoodlePlugin'
        }
    }
}

repositories {
    mavenCentral()
    maven {
        name 'minecraftforge'
        url 'https://maven.minecraftforge.net/'
    }
    maven {
        name 'cursemaven'
        url 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    flatDir {
        dir 'libs'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${MC_VERSION}-${forge_version}"

    compileRequired fg.deobf(group: 'local', name: 'Mekanism', version: '1.12.2-9.8.3.390')
    compileRequired fg.deobf(group: 'local', name: 'IC2Classic', version: '1.12-1.5.8')
    compileRequired files('libs/buildcraft-all-7.99.24.8.jar')
    
    compileOnly fg.deobf(group: 'local', name: 'BiomesOPlenty', version: '1.12.2-7.0.1.2445-universal')
    compileOnly fg.deobf(group: 'local', name: 'appliedenergistics2', version: 'rv6-stable-7')
    compileOnly fg.deobf(group: 'local', name: 'RedstoneFlux', version: '1.12-2.1.1.1-universal')
    compileOnly fg.deobf(group: 'local', name: 'ActuallyAdditions', version: '1.12.2-r152')
    compileOnly fg.deobf(group: 'local', name: 'PlayerAPI', version: '1.12.2-1.0')
    compileOnly fg.deobf(group: 'local', name: 'journeymap', version: '1.12.2-5.7.1')
    compileOnly fg.deobf(group: 'local', name: 'jei_1.12.2', version: '4.16.1.1003')
    runtimeOnly fg.deobf(group: 'local', name: 'jei_1.12.2', version: '4.16.1.1003')
    
    // Project lombok
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    testCompileOnly 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
}

spotless {
	enforceCheck false
    java {
        target 'src/*/java/micdoodle8/mods/**/*.java'
        endWithNewline()
        trimTrailingWhitespace()
        removeUnusedImports()
        indentWithSpaces()
    }
}

license {
    header = project.file('etc/HEADER')
    properties {
        company = 'Team Galacticraft'
        year = Calendar.getInstance().get(Calendar.YEAR);
    }
    ignoreFailures = true
    include '**/*.java'
}

clean {
    def filteredDelete = new HashSet<>()
    for (def toDelete : getDelete()) {
        for (def f : file(toDelete).listFiles()) {
            if (f.getName() != "fg_cache") {
                filteredDelete.add(f)
            }
        }
    }
    setDelete(filteredDelete)
}

// tokens {
//     replace('version', version)
// }

// changelog {
// 	fromTag('4.0.5')
// }

// maven {
// 	excludeDependencies('forge', 'jei')
// 	artifacts(mavenJar, deobfJar, sourcesJar)
// }


// modpublishing {
// 
// 	changelogPath(changelog.changelogFile)
// 
//     curseforge('564236') {
//     	if (System.getenv().CI)
//     		apiKey = 'none'
// 	    relations {
// 	        optional(
// 	        	'mekanism',
// 	        	'jei', 
// 	        	'journeymap',
// 	        	'playerapi', 
// 	        	'actually-additions',
// 	        	'redstone-flux', 
// 	        	'applied-energistics-2',
// 	        	'biomes-o-plenty', 
// 	        	'buildcraft',
// 	        	'industrial-craft'
// 	        )
// 	        incompatible(
// 	        	'betterportals' ,
// 	        	'vics-modern-warfare-mod'
// 	        )
// 	    }
// 	}
// 
// 	modrinth('ZnmdXAk2') {
// 		if (System.getenv().CI)
//     		token('none')
// 		dependencies {
// 			// Mekanism
// 			optional.version 'KIzASRO5'
// 			// JourneyMap
// 			optional.version 'vacvhRKp'
// 		}
// 	}
// }

processResources {
    inputs.property "version", project.version

    filesMatching("mcmod.info") {
        expand "version": project.version
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": "Galacticraft",
            "Specification-Vendor": "TeamGalacticraft",
            "Specification-Version": project.version,
            "Implementation-Title": "Galacticraft",
            "Implementation-Version": project.version,
            "Implementation-Vendor": "TeamGalacticraft",
            "Implementation-Build-Date": new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(new java.util.Date()),
            "FMLAT": "accesstransformer.cfg",
            "FMLCorePluginContainsFMLMod": "true",
            "FMLCorePlugin": "micdoodle8.mods.miccore.MicdoodlePlugin",
            "Built-On-Minecraft": MC_VERSION,
            "Built-On-Forge": forge_version,
            "Built-On-Mapping": "${mapping_channel}-${mapping_version}",
            "Built-Using": "ForgeGradle: 6.+"
        ])
    }
    archiveBaseName = "Galacticraft"
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.whenTaskAdded { task ->
    if (task.name == 'runClient') {
        task.dependsOn(jar)
    }
    if (task.name == 'runServer') {
        task.dependsOn(jar)
    }
}
